import '../../domain/entities/media_entry.dart';
import '../../domain/entities/media_item.dart';
import '../../domain/entities/media_user_state.dart';

final List<MediaEntry> demoMediaEntries = <MediaEntry>[
  _entry(
    id: 'abp-984',
    fileName: 'ABP-984.mp4',
    title: 'ABP-984',
    actors: <String>['Arina Hashimoto'],
    minutes: 134,
    progress: 0.56,
    rating: 8.5,
    hoursAgo: 2,
  ),
  _entry(
    id: 'ipzz-121',
    fileName: 'IPZZ-121.mkv',
    title: 'Nightfall Protocol',
    actors: <String>['Mio Sato'],
    minutes: 118,
    progress: 0.18,
    rating: 7.8,
    hoursAgo: 9,
  ),
  _entry(
    id: 'mide-902',
    fileName: 'MIDE-902.mp4',
    title: 'MIDE-902',
    actors: <String>['Yua Aida'],
    minutes: 124,
    progress: 0.0,
    rating: null,
    hoursAgo: 15,
  ),
  _entry(
    id: 'star-998',
    fileName: 'STAR-998.mp4',
    title: 'STAR-998',
    actors: <String>['Aya Komi'],
    minutes: 142,
    progress: 0.71,
    rating: 9.1,
    hoursAgo: 20,
  ),
  _entry(
    id: 'same-073',
    fileName: 'SAME-073.mp4',
    title: 'SAME-073',
    actors: <String>['Kanon Imai'],
    minutes: 132,
    progress: 0.34,
    rating: 8.2,
    hoursAgo: 25,
  ),
  _entry(
    id: 'abf-110',
    fileName: 'ABF-110.mkv',
    title: 'ABF-110',
    actors: <String>['Rina Yuu'],
    minutes: 96,
    progress: 0.0,
    rating: 7.0,
    hoursAgo: 30,
  ),
  _entry(
    id: 'ssis-813',
    fileName: 'SSIS-813.mp4',
    title: 'SSIS-813',
    actors: <String>['Nao Kiri'],
    minutes: 128,
    progress: 0.0,
    rating: 8.0,
    hoursAgo: 38,
  ),
  _entry(
    id: 'juq-552',
    fileName: 'JUQ-552.mp4',
    title: 'JUQ-552',
    actors: <String>['Ena Arai'],
    minutes: 119,
    progress: 0.27,
    rating: 7.5,
    hoursAgo: 42,
  ),
  _entry(
    id: 'midv-640',
    fileName: 'MIDV-640.mp4',
    title: 'MIDV-640',
    actors: <String>['Sena Aki'],
    minutes: 126,
    progress: 0.62,
    rating: 8.9,
    hoursAgo: 48,
  ),
  _entry(
    id: 'adn-561',
    fileName: 'ADN-561.mp4',
    title: 'ADN-561',
    actors: <String>['Yuri Nao'],
    minutes: 113,
    progress: 0.0,
    rating: null,
    hoursAgo: 53,
  ),
  _entry(
    id: 'wanz-1942',
    fileName: 'WANZ-1942.mkv',
    title: 'WANZ-1942',
    actors: <String>['Karen Mio'],
    minutes: 109,
    progress: 0.0,
    rating: 6.8,
    hoursAgo: 61,
  ),
  _entry(
    id: 'roe-307',
    fileName: 'ROE-307.mp4',
    title: 'ROE-307',
    actors: <String>['Moka Rin'],
    minutes: 143,
    progress: 0.43,
    rating: 8.6,
    hoursAgo: 70,
  ),
];

MediaEntry _entry({
  required String id,
  required String fileName,
  required String title,
  required List<String> actors,
  required int minutes,
  required double progress,
  required double? rating,
  required int hoursAgo,
}) {
  final now = DateTime.now();
  final duration = Duration(minutes: minutes);
  final position = Duration(
    milliseconds: (duration.inMilliseconds * progress).round(),
  );
  final item = MediaItem(
    id: id,
    sourceId: 'demo-source',
    title: title,
    displayLabel: title,
    actorNames: actors,
    fileName: fileName,
    durationMs: duration.inMilliseconds,
    firstSeenAt: now.subtract(Duration(days: 30)),
    lastSeenAt: now.subtract(Duration(hours: hoursAgo)),
    createdAt: now.subtract(Duration(days: 30)),
    updatedAt: now.subtract(Duration(hours: hoursAgo)),
  );

  return MediaEntry(
    item: item,
    userState: MediaUserState(
      mediaId: id,
      ratingValue: rating,
      lastPositionMs: progress <= 0 ? null : position.inMilliseconds,
      durationMsSnapshot: duration.inMilliseconds,
      lastPlayedAt: now.subtract(Duration(hours: hoursAgo)),
      playCount: progress <= 0 ? 0 : 1,
      isFinished: progress >= 0.95,
    ),
  );
}
